[book]
authors = ["The AeroRust community <aerospace.rust@gmail.com>"]
language = "bg"
multilingual = false
src = "."
title = "Сборник за Космическа Конфереция - Пловдив (2023)"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
# extra-watch-dirs = ["."]